/**
 * Test script — submits a fake intake form to the local dev server.
 * Usage: npx tsx src/scripts/test-submit.ts
 * Optional env override: TEST_BASE_URL=http://localhost:3001 npx tsx src/scripts/test-submit.ts
 */

import fs from 'fs';
import path from 'path';

// ── Load .env.local ────────────────────────────────────────────────────────────

function loadEnvLocal() {
  const envPath = path.resolve(process.cwd(), '.env.local');
  if (!fs.existsSync(envPath)) {
    console.warn('⚠  .env.local not found — relying on existing env vars');
    return;
  }
  // Collect all pairs first (last value wins for duplicate keys, matching Next.js behaviour)
  const pairs = new Map<string, string>();
  for (const line of fs.readFileSync(envPath, 'utf-8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (key) pairs.set(key, val);
  }
  // Apply — don't override vars already set in the shell environment
  for (const [key, val] of pairs) {
    if (!process.env[key]) process.env[key] = val;
  }
}

loadEnvLocal();

// ── Config ─────────────────────────────────────────────────────────────────────

const BASE_URL = process.env.TEST_BASE_URL ?? 'http://localhost:3000';
const ADMIN_SECRET = process.env.INTAKE_ADMIN_SECRET;

if (!ADMIN_SECRET) {
  console.error('❌  INTAKE_ADMIN_SECRET not set in .env.local');
  process.exit(1);
}

// ── Helpers ────────────────────────────────────────────────────────────────────

async function post(path: string, body: unknown, headers: Record<string, string> = {}) {
  const res = await fetch(`${BASE_URL}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...headers },
    body: JSON.stringify(body),
  });
  const json = await res.json().catch(() => null);
  return { ok: res.ok, status: res.status, json };
}

// ── Main ───────────────────────────────────────────────────────────────────────

async function main() {
  // Step 1: generate a test token
  console.log(`\n🔗  Generating test token via ${BASE_URL}/api/intake/generate-token …`);

  const tokenRes = await post(
    '/api/intake/generate-token',
    { client_name: 'Test Client', client_email: 'test@example.com' },
    { Authorization: `Bearer ${ADMIN_SECRET}` },
  );

  if (!tokenRes.ok) {
    console.error('❌  Failed to generate token:', tokenRes.status, tokenRes.json);
    process.exit(1);
  }

  const { token, url, expires_at } = tokenRes.json as { token: string; url: string; expires_at: string };
  console.log('✅  Token generated');
  console.log('   URL:', url);
  console.log('   Expires:', expires_at);

  // Step 2: submit the fake form
  const fakeForm = {
    token,

    // Step 1 — Your Details
    full_name: 'Test Client',
    preferred_name: 'Testy',
    email: 'test@example.com',
    phone: '+353 87 000 0000',
    date_of_birth: '01/01/1990',
    pronouns: 'they/them',

    // Step 2 — Session Preferences
    session_format: 'online',
    referral_source: 'Google search',
    referral_source_other: '',

    // Step 3 — About You
    reason_for_therapy: 'Testing the intake form PDF and email pipeline. This is a test submission — please ignore.',
    diagnosed_conditions: 'None (test)',
    previous_therapy: 'yes',
    previous_therapy_details: 'Worked with a therapist for 6 months in 2022.',
    current_medication: 'None',

    // Step 4 — Other Support
    seeing_psychiatrist: 'no',
    psychiatrist_details: '',
    uses_ai_tools: 'sometimes',

    // Step 5 — Emergency Contact
    emergency_contact_name: 'Jane Test',
    emergency_contact_phone: '+353 87 111 1111',
    emergency_contact_relationship: 'Partner',

    // GP Details
    gp_name: 'Dr. Test GP',
    gp_practice: 'Test Medical Centre, Dublin',

    // Additional
    additional_info: 'This is an automated test submission generated by test-submit.ts.',

    // Step 6 — Consent
    consent_data_storage: true,
    consent_age_confirmation: true,
  };

  console.log(`\n📤  Submitting form to ${BASE_URL}/api/intake/submit …`);

  const submitRes = await post('/api/intake/submit', fakeForm);

  if (!submitRes.ok) {
    console.error('❌  Submission failed:', submitRes.status, submitRes.json);
    process.exit(1);
  }

  console.log('✅  Form submitted successfully');
  console.log('\n📧  Check the terminal running the dev server for email/PDF logs.');
  console.log('📋  Check /admin/intake — the submission should appear in the "Submitted forms" table.\n');
}

main().catch(err => {
  console.error('❌  Unexpected error:', err);
  process.exit(1);
});
